#flutter pub run flutter_native_splash:create --flavor bmcargo
#flutter pub run flutter_native_splash:create --flavor domex
#flutter pub run flutter_native_splash:create --flavor caribepack
#flutter pub run flutter_native_splash:create --flavor taino
#flutter pub run flutter_native_splash:create --flavor tls
#flutter pub run flutter_native_splash:create --flavor cainca
#flutter pub run flutter_native_splash:create --flavor tupaq
#flutter pub run flutter_native_splash:create --flavor fixocargo
#flutter pub run flutter_native_splash:create --flavor cps
#flutter pub run flutter_native_splash:create --flavor pintopaq
#flutter pub run flutter_native_splash:create --flavor encargopaq
#flutter pub run flutter_native_splash:create --flavor almapaq
#flutter pub run flutter_native_splash:create --flavor beexpress
#flutter pub run flutter_native_splash:create --flavor picknsend
#flutter pub run flutter_native_splash:create --flavor priority
#flutter pub run flutter_native_splash:create --flavor qm
#flutter pub run flutter_native_splash:create --flavor clickpack
#flutter pub run flutter_native_splash:create --flavor jetpack
#flutter pub run flutter_native_splash:create --flavor swoop
flutter pub run flutter_native_splash:create --flavor skyhigh
#flutter pub run flutter_native_splash:create --flavor blumbox
#flutter pub run flutter_native_splash:create --flavor flypack